    export const courses = [
        {
            id: 1,
            title: 'Testiranje i kvaliteta programskih proizvoda',
            code: '82157',
            major: 'Informacijski i poslovni sustavi 1.2 (IPS)',
            semester: 6,
            ects: 6,
            katedra: 'Katedra za rzvoj informacisjkih sustava',
            profesors: ['Kitinić Valentina' , 'Mijač Marko', 'Berket Marijana'],
            years: [2020, 2021, 2022, 2023, 2024],
        },
        {
            id: 2,
            title: 'Projektiranje informacijskih sustava',
            code: '574978',
            major: 'Informacijski i poslovni sustavi 1.2 (IPS)',
            semester: 3,
            ects: 7,
            katedra: 'Katedra za rzvoj informacisjkih sustava',
            profesors: ['Andročec Darko' , 'Strahonja Vjeran', 'Oreški Dijana'],
            years: [2020, 2021, 2022, 2023, 2024],
        },
        {
            id: 3,
            title: 'Razvoj windows aplikacija',
            code: '453423',
            major: 'Informacijski i poslovni sustavi 1.2 (IPS)',
            semester: 4,
            ects: 4,
            katedra: 'Katedra za rzvoj informacisjkih sustava',
            profesors: ['Stapić Zlatko' , 'Mijač Marko', 'Masnec Lea', 'Takač Kristina', 'Klarić Vedran'],
            years: [2023, 2024],
        },
        {
            id: 4,
            title: 'Analiza i razvoj programa',
            code: '345678',
            major: 'Informacijski i poslovni sustavi 1.2 (IPS)',
            semester: 4,
            ects: 4,
            katedra: 'Katedra za rzvoj informacisjkih sustava',
            profesors: ['Stapić Zlatko' , 'Vrček Neven', 'Masnec Lea', 'Klarić vedran'],
            years: [2020, 2021,],
        },
    ];